version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/student_registration
      - VALIDATION_SERVICE_URL=http://microservice:4000
    depends_on:
      - mongodb
      - microservice

  microservice:
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: