apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: student-registration-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-registration-backend
  template:
    metadata:
      labels:
        app: student-registration-backend
    spec:
      containers:
      - name: backend
        image: student-registration-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: student-registration-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP